# 指定docker-compose版本
version: '3.8'

services:
  # Spring Boot应用服务配置
  app:
    build: .  # 使用当前目录的Dockerfile构建
    image: juneink/thrivex-server:latest
    container_name: thrivex-server
    networks:
      - thrivex-network
    environment:
      # 数据库连接配置
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/thrivex?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 123456
    ports:
      - "8080:8080"  # 只暴露应用端口

# 网络配置
networks:
  thrivex-network:
    external: true  # 使用外部已存在的网络

# 数据卷配置
volumes:
  mysql_data:  # MySQL数据持久化卷 