# Docker构建和部署工作流
name: Docker Build and Deploy

# 触发条件：推送到main分支、PR到main分支，或手动触发
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    # 下载最新版本的blog.jar文件
    - name: Download latest blog.jar
      run: |
        LATEST_RELEASE_URL=$(curl -s https://api.github.com/repos/LiuYuYang01/ThriveX-Server/releases/latest | grep "browser_download_url.*blog.jar" | cut -d '"' -f 4)
        curl -L -o blog.jar $LATEST_RELEASE_URL
    
    # 设置Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1
    
    # 登录到Docker Hub
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    # 构建并推送Docker镜像
    - name: Build and push
      run: |
        docker compose build
        docker compose push 